### ISSUE TITLE
how to use lezer-promql without codemirror?

### ISSUE THREAD

**Issue by gabor** [promlabs/lezer-promql#41]
hi, i'm using lezer-promql in a not codemirror-based project, and i see that this package was merged into codemirror-promql.

it seems it is now impossible to use this code in a non-codemirror project, but maybe (hopefully 😄 ) there is some approach that i am just overlooking... so, is there some way to use the new code without using codemirror? thanks!

**Comment by Nexucis** [comment]
Hi,

ah unfortunately there is no way that comes in my mind to use `lezer-promql` without `codemirror-promql` (at least currently)

We did that, because we assumed (and it appears, wrongly) `lezer-promql` wasn't used without `codemirror-promql` because `codemirror-promql` provides a lot of functionality on top of `lezer-promql`.

I'm curious, would you be ok to explain how are you using `lezer-promql` without codemirror ?

One idea that comes to my mind would be to sync this repo with the changes performed in prometheus/prometheus (with mirror thingy, like we did for `codemirror-promql`).
But for that the current repo would have to be moved to the org `prometheus-community`. So it will depend on what @juliusv thinks about it.

**Comment by gabor** [comment]
> I'm curious, would you be ok to explain how are you using `lezer-promql` without codemirror ?

we are moving to a monaco-powered prometheus query-editor-field in https://github.com/grafana/grafana , and we use `lezer-promql` in the autocomplete-code (`lezer-promql` builds the syntax tree, we find the cursor in it, and offer autocomplete suggestions based on that)... this is not finished yet, still in-progress, but the code is already there, behind an opt-in feature-flag.

(we are also using `monaco-promql`, but that does not have a good autocomplete-solution, so we use `lezer-promql` for the autocomplete-part, and `monaco-promql` for the rest (syntax highlighting, etc.)

> 
> One idea that comes to my mind would be to sync this repo with the changes performed in prometheus/prometheus (with mirror thingy, like we did for `codemirror-promql`). But for that the current repo would have to be moved to the org `prometheus-community`. So it will depend on what @juliusv thinks about it.

the idea to sync changes back to this repo sounds great, would help a lot 👍 , but worst case we can also just take the lezer-grammar-files from the prometheus-repo and build the parser manually for grafana.

**Comment by juliusv** [comment]
When we start publishing npm packages from https://github.com/prometheus-community/codemirror-promql/, it would be possible to import `codemirror-promql` again and just use the lezer bits from that, or are those currently not exposed properly? While that wouldn't require actually using Codemirror, I guess the dependency (and its CM peer dependencies) is still larger than necessary then. If that's not a good-enough solution, we could make `lezer-promql` its own sub-package in the Prometheus repo, just as it is for `codemirror-promql` right now. And then we'd sync it for versioning+publishing to a separate repo (just like `codemirror-promql`), but then I'd prefer the mirror to live in the `prometheus-community` org (or even the `prometheus` org) as well, since it's such an integral part of Prometheus.

**Comment by Nexucis** [comment]
> we use lezer-promql in the autocomplete-code

I don't know if it's feasible, but wouldn't be interesting for you @gabor to use the autocomplete code implemented in `codemirror-promql` ? So you don't have (re)implement the logic about what should be autocompleted depending on the cursor position.

>  it would be possible to import codemirror-promql again and just use the lezer bits from that, or are those currently not exposed properly

I think the issue here is the `peer-dependencies` and with latest version of npm (or probably yarn), you cannot use a package without installing the `peer-dependencies` required @juliusv . 

> we could make lezer-promql its own sub-package in the Prometheus repo

I don't know if it's entirely feasible, since `codemirror-promql` would depend on a local package. Once it lives in `codemirror-promql` then the package will depend on a unpublished package so the CI won't work :(

**Comment by gabor** [comment]
> When we start publishing npm packages from https://github.com/prometheus-community/codemirror-promql/, it would be possible to import `codemirror-promql` again and just use the lezer bits from that, or are those currently not exposed properly? While that wouldn't require actually using Codemirror, I guess the dependency (and its CM peer dependencies) is still larger than necessary then.

i'm not sure about the exports being correct or not, but i'd be worried about the peerdeps, as you also mentioned.

> If that's not a good-enough solution, we could make `lezer-promql` its own sub-package in the Prometheus repo, just as it is for `codemirror-promql` right now. And then we'd sync it for versioning+publishing to a separate repo (just like `codemirror-promql`), but then I'd prefer the mirror to live in the `prometheus-community` org (or even the `prometheus` org) as well, since it's such an integral part of Prometheus.

to be honest i'm not sure i understand the details here 😄 , but as long as at the end there is a npm-package with content like the current `lezer-promql`, that is good enough.

**Comment by gabor** [comment]
> > we use lezer-promql in the autocomplete-code
> 
> I don't know if it's feasible, but wouldn't be interesting for you @gabor to use the autocomplete code implemented in `codemirror-promql` ? So you don't have (re)implement the logic about what should be autocompleted depending on the cursor position.

it's an interesting idea, i also thought about not having to re-implement things, but i see two potential problems:
1. right now i don't see a way to access that functionality without having to add the codemirror peerdependency, so this would mean to somehow extract that code into some separate thing, i guess?
2. we might have to customize the autocomplete logic to integrate better with Grafana, so maybe we would have to write custom code at the end anyway.

**Comment by Nexucis** [comment]
> right now i don't see a way to access that functionality without having to add the codemirror peerdependency, so this would mean to somehow extract that code into some separate thing, i guess?

Ah yeah that's right, you will have the codemirror dependency issue. And could it be an option to actually use codemirror as a code editor ? Or even just the different type used for the autocompletion.  
Worst case will be the copy / past the code with a comment saying `this code is duplicated from prometheus-community/codemirror-promql`. 

> we might have to customize the autocomplete logic to integrate better with Grafana, so maybe we would have to write custom code at the end anyway.

I am maybe a bit partial here since I wrote most of the code around the autocomplete feature. 
I would be really interesting to know what would be these customizations required for Grafana only. I mean, probably we missed some use cases that could be integrated into the code.

**Comment by Nexucis** [comment]
So probably we can start by moving the repo in the `prometheus` org, or in the `prometheus-community`. Perhaps it could be nice it's in the same org than `codemirror-promql` right @juliusv. I don't have a strong opinion where it should go.

**Comment by juliusv** [comment]
@Nexucis At this point I think we should probably also move `codemirror-promql` to `prometheus`, since it's now an official part of Prometheus, although it started out as a community satellite thing. TBH I have little time to spend on this myself at the moment, but am very supportive of anyone who wants to do that move or generally wants to make things (like `lezer`) more reusable outside of Prometheus and CodeMirror!

**Comment by Nexucis** [comment]
cool thanks for your answer @juliusv. I will send an email to the prometheus developer to see what they think about this, and then if they are agree, I will take care about the next steps.
Hopefully that shouldn't be too complicated to resync the `lezer-promql`.

**Comment by gabor** [comment]
> > we might have to customize the autocomplete logic to integrate better with Grafana, so maybe we would have to write custom code at the end anyway.
> 
> I am maybe a bit partial here since I wrote most of the code around the autocomplete feature. I would be really interesting to know what would be these customizations required for Grafana only. I mean, probably we missed some use cases that could be integrated into the code.

@Nexucis i agree, it would make sense to reuse the code, i will look into how it could be possible.

**Comment by Nexucis** [comment]
> @Nexucis I agree, it would make sense to reuse the code, i will look into how it could be possible.

cool @gabor looking forward if you need some help or some changes in the API exposed.

In the meantime, we are going to move this repository to the Prometheus org and to enable the sync between the code living in prometheus/prometheus and this one.

So hopefully soon this repo will be re-enable.

**Comment by Nexucis** [comment]
the package is now available under the prometheus org and published as `@prometheus-io/lezer-promql`
We can now close this issue as solved :).
Sorry for the long delay, it took me much more time that expected to make the migration.
